tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/cert.pem
        keyFile: /etc/ssl/traefik/privkey.pem

http:
  middlewares:
    fcrepo-strip-suffix:
      replacePathRegex:
        regex: "^(.*/fcrepo/rest/[^.]*)/fcr:metadata$"
        replacement: "$1"
    cantaloupe-custom-request-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Path: /cantaloupe
    cantaloupe-strip-prefix:
      stripPrefix:
        prefixes:
          - /cantaloupe
    cantaloupe-chain:
      chain:
        middlewares:
          - cantaloupe-strip-prefix
          - cantaloupe-custom-request-headers

